# Generated by Django 5.0.3 on 2024-04-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(blank=True, null=True)),
                ('title', models.CharField(blank=True, null=True)),
                ('role', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
