# Generated by Django 5.0.3 on 2024-04-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0003_story_completed_alter_story_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(blank=True, default=False, null=True),
        ),
    ]
