# Generated by Django 5.0.3 on 2024-04-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, null=True)),
                ('dialogue', models.CharField(blank=True, null=True)),
                ('choice_one', models.CharField(blank=True, null=True)),
                ('choice_two', models.CharField(blank=True, null=True)),
                ('choice_three', models.CharField(blank=True, null=True)),
            ],
        ),
    ]
