# Generated by Django 5.0.3 on 2024-04-04 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('progress_app', '0001_initial'),
        ('story_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress', to='story_app.story'),
        ),
    ]
