# Generated by Django 5.0.3 on 2024-04-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='danger_one',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='danger_three',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='danger_two',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='title',
            field=models.CharField(blank=True, null=True),
        ),
    ]
