# Generated by Django 5.0.3 on 2024-04-13 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_app', '0004_progress_decision_progress_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='epilogue',
            field=models.CharField(blank=True, null=True),
        ),
    ]
